### PR TITLE
chore: installation includes bagua-net

### PR DESCRIPTION
**Pull request by shjwudp**

### CODE REVIEW

**Comment by shjwudp** [comment]
Add bagua-net into bagua-core's installation dependency

**Review by NOBLES5E — CHANGES_REQUESTED** [review]
I feel like Bagua Net should always be installed but users can choose to enable it or not when running a task (conditionally import it in `environment.py`).

**Comment by shjwudp** [comment]
> I feel like Bagua Net should always be installed but users can choose to enable it or not when running a task (conditionally import it in `environment.py`).

Now always install bagua-net, users can choose to set `ld_library_path` to control whether to use

**Review by NOBLES5E — CHANGES_REQUESTED** [review]
need to determine whether to use bagua net during runtime

**Comment by shjwudp** [comment]
> need to determine whether to use bagua net during runtime

I will add in bagua launch separately to start bagua-net at runtime

**Pull request merged**
